name: firstshot_app
description: "Another Project by Reconshield Network | Reconshield.Com"
publish_to: 'none'

version: 1.0.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  flutter_datetime_picker: ^1.5.0
  url_launcher: ^6.2.6
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.6
  mailer: ^6.0.1
  http: ^1.4.0
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0 
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  webview_flutter: ^4.8.0
  # Removed Firebase dependencies as we're now using Laravel backend
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.3
  # cloud_firestore: ^5.4.3
  # firebase_storage: ^12.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/group.svg
